### ISSUE TITLE
If a logged-in user closes their browser, the session is lost

### ISSUE THREAD

**Issue by robinsk1** [mikker/passwordless#68] opened 2019-10-23 15:24 UTC
Would it be worthwhile offering a choice of cookie/session based authentication to allow the user to stay logged in after a browser restart?

**Comment by mikker** [comment] 2019-10-23 19:07
I was confused by this too. When using a cookie or database based session store, sessions _should be_ persistent between browser sessions.

**Comment by robinsk1** [comment] 2019-10-24 10:09
if i add `expire_after: 5.minutes` to `initializers/session_store.rb` my session _is persisted_ (previously i had that left out) between browser sessions...though in testing it does seem to persist much longer than 5 minutes which is slightly odd

**Comment by mikker** [comment] 2019-10-24 12:01
I thought the default was to never expire.

**Comment by mikker** [comment] 2020-01-17 12:46
Closing as I think the question was answered. Feel free to reopen if that's not the case.

**Closed by mikker** 2020-01-17 12:46 UTC

**Comment by z3ugma** [comment] 2020-06-05 01:09
I'm having a similar issue where in localhost / development mode, 2 cookies are set by a default Rails 6.0 app with passwordless.
One cookie, `_app_session`, is the regular Rails session. Then, there's `_session_id` which is the passwordless session cookie.

This cookie is being properly set in development, but not in production.

**Comment by mikker** [comment] 2020-06-09 08:09
If you are on the latest version of Passwordless, there's nothing special about the way Passwordless saves the session, so the issue is probably related to Rails, not Passwordless specifically.
